构建数据类型

In [1]:
import tensorflow as tf

标量 

In [2]:
x = tf.constant(1.2)
print(type(x))
print(x)

<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(1.2, shape=(), dtype=float32)


In [3]:
b=tf.constant([1,2.,3.3])
print(b)#可以打印出张量的相关信息

tf.Tensor([1.  2.  3.3], shape=(3,), dtype=float32)


In [4]:
#定义一个矩阵
a=tf.constant([[1,2],[3,4]])
print(a)
print(a.shape)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
(2, 2)


In [5]:
#3维张量的定义
c=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.shape)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
(2, 2, 2)


In [6]:
#定义字符串
a=tf.constant('HELLO,deep learning')
a

<tf.Tensor: shape=(), dtype=string, numpy=b'HELLO,deep learning'>

In [7]:
#布尔类型
a=tf.constant(True)
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>